// src/content/games.ts
import type { GameDefinition } from './types';

export const GAMES_REGISTRY: Record<string, GameDefinition> = {
  // --- LEVEL 1 GAMES ---
  G1: {
    id: 'G1',
    name: 'Side Sniper',
    level: 1,
    skills: ['E1'],
    tagline: 'Rapid target labeling under rotational drift',
    description: 'Triangles appear at random rotations. Tap the Hypotenuse, Opposite, or Adjacent side relative to θ before time expires.',
    runLength: 10,
    litThreshold: 0.7,
    calmSupported: true,
  },
  G2: {
    id: 'G2',
    name: 'Ratio Rush',
    level: 1,
    skills: ['E2', 'E3'],
    tagline: 'Arcade sorting of fundamental fraction ratios',
    description: 'Fraction cards fall from the sky. Drag each fraction to the correct lane: Sine, Cosine, or Tangent.',
    runLength: 10,
    litThreshold: 0.7,
    calmSupported: true,
  },
  G3: {
    id: 'G3',
    name: 'Height Hunter',
    level: 1,
    skills: ['E5', 'E6', 'E8'],
    tagline: 'Real-world field surveying exploration',
    description: 'Aim your virtual clinometer at towers, kites, and lighthouses, then calculate the unknown height using SCALE.',
    runLength: 6,
    litThreshold: 0.7,
    calmSupported: true,
  },
  G4: {
    id: 'G4',
    name: 'Trick Duel',
    level: 1,
    skills: ['E4', 'E7'],
    tagline: 'High-speed exact value reflexes against Theo',
    description: 'Theo flashes an angle like sin 60° or cos 45°. Tap the exact surd value tile as fast as you can.',
    runLength: 10,
    litThreshold: 0.7,
    calmSupported: true,
  },
  G5: {
    id: 'G5',
    name: 'Error Detective',
    level: 1,
    skills: ['E1', 'E2', 'E5', 'E6'],
    tagline: 'Spot the bug in student notebook calculations',
    description: 'A student worked solution is displayed with exactly ONE flawed line. Tap the broken step and name the misconception.',
    runLength: 6,
    litThreshold: 0.7,
    calmSupported: true,
  },

  // --- LEVEL 2 GAMES ---
  G6: {
    id: 'G6',
    name: 'Quadrant Painter',
    level: 2,
    skills: ['M6', 'M7', 'M8', 'M9'],
    tagline: 'Light up quadrants where ratio signs match',
    description: 'Paint the quadrants of the Cartesian plane where given trigonometric functions are positive or negative.',
    runLength: 8,
    litThreshold: 0.7,
    calmSupported: true,
  },
  G7: {
    id: 'G7',
    name: 'Unit Circle Runner',
    level: 2,
    skills: ['M6', 'M7', 'M8'],
    tagline: 'Steer the orb through coordinate checkpoints',
    description: 'Navigate an orb around the unit circle, passing through gates by declaring angles, coordinates, and exact values.',
    runLength: 10,
    litThreshold: 0.7,
    calmSupported: true,
  },
  G8: {
    id: 'G8',
    name: 'Radian Match-Up',
    level: 2,
    skills: ['M10', 'M11'],
    tagline: 'Celestial memory pairing of degrees and radians',
    description: 'Flip celestial cards to pair degree measures (e.g. 60°) with their radian twins (π/3) and circular arc lengths.',
    runLength: 8,
    litThreshold: 0.7,
    calmSupported: true,
  },
  G9: {
    id: 'G9',
    name: 'Simplify Race',
    level: 2,
    skills: ['M1', 'M2', 'M3', 'M4', 'M5'],
    tagline: 'Algebraic tile puzzles reducing messy expressions',
    description: 'Select algebraic transform cards to reduce trigonometric expressions down to 1, sec θ, or clean surds in minimal moves.',
    runLength: 8,
    litThreshold: 0.7,
    calmSupported: true,
  },

  // --- LEVEL 3 GAMES ---
  G10: {
    id: 'G10',
    name: 'Proof Builder',
    level: 3,
    skills: ['H1'],
    tagline: 'Order transformation steps to prove identities',
    description: 'Slot algebraic lines into an identity proof and assign the correct justification move to each link.',
    runLength: 5,
    litThreshold: 0.7,
    calmSupported: true,
  },
  G11: {
    id: 'G11',
    name: 'Wave Tuner',
    level: 3,
    skills: ['H8'],
    tagline: 'Tune amplitude, period, and phase on an oscilloscope',
    description: 'Adjust frequency dials A, B, C, D to tune your wave to resonate with target acoustic and seismic signals.',
    runLength: 6,
    litThreshold: 0.7,
    calmSupported: true,
  },
  G12: {
    id: 'G12',
    name: 'Triangle Verdict',
    level: 3,
    skills: ['H5', 'H6', 'H7'],
    tagline: 'Courtroom verdict on non-right triangles',
    description: 'Examine partial triangle evidence: which rule applies? And how many triangles exist in the ambiguous SSA case? (0, 1, or 2).',
    runLength: 8,
    litThreshold: 0.7,
    calmSupported: true,
  },
  G13: {
    id: 'G13',
    name: 'Solution Sweep',
    level: 3,
    skills: ['H9', 'H10'],
    tagline: 'Sweep graphs to tag every intersection solution',
    description: 'Solve trigonometric equations over [0, 2π) and sweep the curve to tag every valid solution point.',
    runLength: 8,
    litThreshold: 0.7,
    calmSupported: true,
  },
  G14: {
    id: 'G14',
    name: 'Exact or Bust',
    level: 3,
    skills: ['H2', 'H3', 'M5'],
    tagline: 'Assemble non-standard exact surds like 75° and 15°',
    description: 'Pick an angle split (45° + 30°), apply the compound angle formula, and assemble canonical exact surds.',
    runLength: 8,
    litThreshold: 0.7,
    calmSupported: true,
  },
};
