// src/content/skills.ts
import type { SkillDefinition } from './types';

export const SKILLS_REGISTRY: Record<string, SkillDefinition> = {
  // --- LEVEL 1: SHADOW SCOUTS (Beginner) ---
  E0: {
    id: 'E0',
    level: 1,
    title: 'Prerequisite Geometry Toolkit',
    isCore: false,
    formulas: ['A + B + C = 180^\\circ', 'a^2 + b^2 = c^2', 'k = \\frac{\\text{new}}{\\text{old}}'],
    description: 'Triangle angle sum, Pythagorean theorem, and similarity scale factors.',
    prerequisites: [],
    misconceptions: ['PYTHAG_ADD_LEG'],
    trickId: 'V1',
  },
  E1: {
    id: 'E1',
    level: 1,
    title: 'Name Triangle Sides Relative to θ',
    isCore: true,
    formulas: ['\\text{Hypotenuse} \\perp 90^\\circ', '\\text{Opposite} \\leftrightarrow \\theta', '\\text{Adjacent} \\cap \\theta'],
    description: 'Label Hypotenuse, Opposite, and Adjacent sides anchored strictly to angle θ.',
    prerequisites: ['E0'],
    misconceptions: ['ADJ_HYP_CONFUSION', 'OPP_ADJ_SWAP'],
  },
  E2: {
    id: 'E2',
    level: 1,
    title: 'The Fundamental Ratios (SOH-CAH-TOA)',
    isCore: true,
    formulas: [
      '\\sin\\theta = \\frac{\\text{opp}}{\\text{hyp}}',
      '\\cos\\theta = \\frac{\\text{adj}}{\\text{hyp}}',
      '\\tan\\theta = \\frac{\\text{opp}}{\\text{adj}}',
    ],
    description: 'Define sine, cosine, and tangent as constant ratios of right-triangle sides.',
    prerequisites: ['E1'],
    misconceptions: ['RATIO_INVERTED', 'RATIO_WRONG_FN'],
    trickId: 'T1',
  },
  E3: {
    id: 'E3',
    level: 1,
    title: 'Scale Invariance of Trigonometric Ratios',
    isCore: true,
    formulas: ['\\frac{k \\cdot \\text{opp}}{k \\cdot \\text{hyp}} = \\frac{\\text{opp}}{\\text{hyp}} = \\sin\\theta'],
    description: 'Understand why ratios depend exclusively on angle tilt, regardless of triangle size.',
    prerequisites: ['E2'],
    misconceptions: [],
  },
  E4: {
    id: 'E4',
    level: 1,
    title: 'Special Angle Exact Values (30°, 45°, 60°)',
    isCore: true,
    formulas: [
      '\\sin 30^\\circ = \\frac{1}{2}, \\; \\sin 45^\\circ = \\frac{\\sqrt{2}}{2}, \\; \\sin 60^\\circ = \\frac{\\sqrt{3}}{2}',
      '\\tan 45^\\circ = 1, \\; \\tan 30^\\circ = \\frac{\\sqrt{3}}{3}, \\; \\tan 60^\\circ = \\sqrt{3}',
    ],
    description: 'Derive exact surd values from half-equilaterals and diagonal unit squares.',
    prerequisites: ['E2'],
    misconceptions: ['SPECIAL_SWAP'],
    trickId: 'T3',
  },
  E5: {
    id: 'E5',
    level: 1,
    title: 'Missing Side Calculation (SCALE Routine)',
    isCore: true,
    formulas: ['\\text{Target} = \\text{Known} \\cdot f(\\theta) \\quad \\text{or} \\quad \\text{Target} = \\frac{\\text{Known}}{f(\\theta)}'],
    description: 'Execute the SCALE routine to solve for any unknown side length.',
    prerequisites: ['E2'],
    misconceptions: ['ONE_STEP_INVERT', 'CALC_MODE'],
    trickId: 'T2',
  },
  E6: {
    id: 'E6',
    level: 1,
    title: 'Missing Angle Calculation (Inverse Ratios)',
    isCore: true,
    formulas: ['\\theta = \\sin^{-1}\\left(\\frac{\\text{opp}}{\\text{hyp}}\\right)'],
    description: 'Use inverse functions to uncoil angles from known side ratios.',
    prerequisites: ['E2'],
    misconceptions: ['INV_AS_RECIPROCAL'],
  },
  E7: {
    id: 'E7',
    level: 1,
    title: 'Complementary Angles Co-Functions',
    isCore: true,
    formulas: ['\\sin\\theta = \\cos(90^\\circ - \\theta)', '\\tan\\theta = \\cot(90^\\circ - \\theta)'],
    description: 'Understand why opposite and adjacent swap across complementary acute angles.',
    prerequisites: ['E1', 'E2'],
    misconceptions: [],
    trickId: 'T4',
  },
  E8: {
    id: 'E8',
    level: 1,
    title: 'Angles of Elevation & Depression',
    isCore: true,
    formulas: ['\\tan(\\text{elevation}) = \\frac{\\text{Height}}{\\text{Distance}}'],
    description: 'Model real-world surveying heights and distances using horizontal baselines.',
    prerequisites: ['E5'],
    misconceptions: ['ELEVATION_FROM_VERTICAL', 'CALC_MODE'],
  },
  E9: {
    id: 'E9',
    level: 1,
    title: 'Pythagorean Triples Speed Radar',
    isCore: false,
    formulas: ['(3, 4, 5), \\; (5, 12, 13), \\; (8, 15, 17), \\; (7, 24, 25)'],
    description: 'Instantly spot primitive and scaled triples to bypass calculation.',
    prerequisites: ['E0'],
    misconceptions: [],
    trickId: 'T6',
  },

  // --- LEVEL 2: CIRCLE CARTOGRAPHERS (Intermediate) ---
  M1: {
    id: 'M1',
    level: 2,
    title: 'Reciprocal Ratios (csc, sec, cot)',
    isCore: true,
    formulas: ['\\csc\\theta = \\frac{1}{\\sin\\theta}', '\\sec\\theta = \\frac{1}{\\cos\\theta}', '\\cot\\theta = \\frac{1}{\\tan\\theta}'],
    description: 'Define and calculate the three reciprocal trigonometric ratios.',
    prerequisites: ['E2'],
    misconceptions: ['RECIPROCAL_VS_INVERSE'],
  },
  M2: {
    id: 'M2',
    level: 2,
    title: 'Quotient Identities',
    isCore: true,
    formulas: ['\\tan\\theta = \\frac{\\sin\\theta}{\\cos\\theta}', '\\cot\\theta = \\frac{\\cos\\theta}{\\sin\\theta}'],
    description: 'Express tangent and cotangent as quotients of sine and cosine.',
    prerequisites: ['E2', 'M1'],
    misconceptions: [],
  },
  M3: {
    id: 'M3',
    level: 2,
    title: 'The Pythagorean Identities',
    isCore: true,
    formulas: ['\\sin^2\\theta + \\cos^2\\theta = 1', '1 + \\tan^2\\theta = \\sec^2\\theta', '1 + \\cot^2\\theta = \\csc^2\\theta'],
    description: 'Derive and apply the fundamental Pythagorean identities.',
    prerequisites: ['M1', 'M2'],
    misconceptions: ['SQUARE_POSITION', 'PYTHAGOREAN_ADDITION'],
  },
  M4: {
    id: 'M4',
    level: 2,
    title: 'Given One Ratio, Find All Remaining',
    isCore: true,
    formulas: ['\\text{Hyp} = \\sqrt{\\text{Opp}^2 + \\text{Adj}^2}'],
    description: 'Construct a reference right triangle to determine all 6 trigonometric ratios.',
    prerequisites: ['M1', 'M3'],
    misconceptions: ['SIGN_AFTER_SQRT'],
  },
  M5: {
    id: 'M5',
    level: 2,
    title: 'Exact Surd Simplification & Rationalization',
    isCore: true,
    formulas: ['\\frac{1}{\\sqrt{n}} = \\frac{\\sqrt{n}}{n}, \\quad \\frac{1}{\\sqrt{a} + \\sqrt{b}} = \\frac{\\sqrt{a} - \\sqrt{b}}{a - b}'],
    description: 'Simplify complex trigonometric expressions into canonical surd forms.',
    prerequisites: ['E4'],
    misconceptions: [],
    trickId: 'T11',
  },
  M6: {
    id: 'M6',
    level: 2,
    title: 'Unit Circle Coordinates Definition',
    isCore: true,
    formulas: ['P(\\theta) = (\\cos\\theta, \\sin\\theta), \\quad x^2 + y^2 = 1'],
    description: 'Define trigonometric functions as Cartesian coordinates on the unit circle.',
    prerequisites: ['E2', 'M3'],
    misconceptions: [],
  },
  M7: {
    id: 'M7',
    level: 2,
    title: 'Signs by Quadrant (ASTC Rule)',
    isCore: true,
    formulas: ['\\text{Q1: All (+)}, \\; \\text{Q2: Sin (+)}, \\; \\text{Q3: Tan (+)}, \\; \\text{Q4: Cos (+) }'],
    description: 'Determine positive/negative signs across all 4 quadrants using ASTC.',
    prerequisites: ['M6'],
    misconceptions: ['SIGN_AFTER_SQRT'],
    trickId: 'T5',
  },
  M8: {
    id: 'M8',
    level: 2,
    title: 'Reference Angles (Any Angle to Acute)',
    isCore: true,
    formulas: ['\\text{Q2: } \\alpha = 180^\\circ - \\theta, \\quad \\text{Q3: } \\alpha = \\theta - 180^\\circ, \\quad \\text{Q4: } \\alpha = 360^\\circ - \\theta'],
    description: 'Fold any angle back to the horizontal x-axis to find its acute reference value.',
    prerequisites: ['M7'],
    misconceptions: ['REF_ANGLE_SLIP'],
  },
  M9: {
    id: 'M9',
    level: 2,
    title: 'Negative & Coterminal Angles',
    isCore: true,
    formulas: ['\\sin(-\\theta) = -\\sin\\theta, \\quad \\cos(-\\theta) = \\cos\\theta, \\quad \\theta \\equiv \\theta + 360^\\circ k'],
    description: 'Exploit odd/even rotational symmetries and coterminal full turns.',
    prerequisites: ['M6'],
    misconceptions: [],
  },
  M10: {
    id: 'M10',
    level: 2,
    title: 'Radians and Degree Conversions',
    isCore: true,
    formulas: ['\\pi \\text{ rad} = 180^\\circ, \\quad 1\\text{ rad} = \\frac{180^\\circ}{\\pi} \\approx 57.3^\\circ'],
    description: 'Understand radians as natural arc measures and convert fluently.',
    prerequisites: ['M6'],
    misconceptions: ['RAD_AS_DEGREES', 'RADIAN_DEGREE_RATIO_FLIP'],
    trickId: 'T7',
  },
  M11: {
    id: 'M11',
    level: 2,
    title: 'Arc Length & Sector Area',
    isCore: true,
    formulas: ['s = r\\theta, \\quad A = \\frac{1}{2}r^2\\theta \\quad (\\theta \\text{ in radians})'],
    description: 'Calculate circular distances and curved sector areas using radians.',
    prerequisites: ['M10'],
    misconceptions: ['CALC_MODE'],
  },
  M12: {
    id: 'M12',
    level: 2,
    title: 'Two-Step Heights & Dual Observation Points',
    isCore: true,
    formulas: ['h = \\frac{d}{\\cot\\alpha - \\cot\\beta}'],
    description: 'Solve simultaneous equations for heights observed from dual baseline stations.',
    prerequisites: ['E8', 'M2'],
    misconceptions: ['CALC_MODE'],
  },
  M13: {
    id: 'M13',
    level: 2,
    title: 'Non-Right Triangle Area (1/2 ab sin C)',
    isCore: false,
    formulas: ['\\text{Area} = \\frac{1}{2}ab\\sin C'],
    description: 'Compute the area of any triangle from two sides and their included angle.',
    prerequisites: ['E2'],
    misconceptions: [],
  },

  // --- LEVEL 3: SKY ENGINEERS (Advanced) ---
  H1: {
    id: 'H1',
    level: 3,
    title: 'Analytic Proof of Trigonometric Identities',
    isCore: true,
    formulas: ['\\text{LHS} \\equiv \\text{RHS} \\quad (\\text{One-Sided Transformation Protocol})'],
    description: 'Prove complex identities systematically without moving terms across the equals sign.',
    prerequisites: ['M3', 'M5'],
    misconceptions: ['MOVE_ACROSS_EQ', 'CANCEL_TRIG_ARGUMENT'],
  },
  H2: {
    id: 'H2',
    level: 3,
    title: 'Compound Angle Formulas (Sum & Difference)',
    isCore: true,
    formulas: [
      '\\sin(A \\pm B) = \\sin A\\cos B \\pm \\cos A\\sin B',
      '\\cos(A \\pm B) = \\cos A\\cos B \\mp \\sin A\\sin B',
    ],
    description: 'Evaluate compound rotations and calculate non-standard values like 75° and 15°.',
    prerequisites: ['M6'],
    misconceptions: ['DISTRIBUTE_SIN'],
  },
  H3: {
    id: 'H3',
    level: 3,
    title: 'Double-Angle & Power-Reducing Formulas',
    isCore: true,
    formulas: [
      '\\sin 2A = 2\\sin A\\cos A',
      '\\cos 2A = \\cos^2 A - \\sin^2 A = 2\\cos^2 A - 1 = 1 - 2\\sin^2 A',
      '\\sin^2 A = \\frac{1 - \\cos 2A}{2}',
    ],
    description: 'Simplify double arguments and reduce high trigonometric powers.',
    prerequisites: ['H2'],
    misconceptions: ['LINEAR_TRIG_DISTRIBUTION'],
    trickId: 'T9',
  },
  H4: {
    id: 'H4',
    level: 3,
    title: 'Product-to-Sum & Acoustic Beat Formulas',
    isCore: false,
    formulas: ['\\sin A\\cos B = \\frac{1}{2}[\\sin(A+B) + \\sin(A-B)]'],
    description: 'Convert between trigonometric products and sums for wave interference modeling.',
    prerequisites: ['H2'],
    misconceptions: [],
  },
  H5: {
    id: 'H5',
    level: 3,
    title: 'The Law of Sines',
    isCore: true,
    formulas: ['\\frac{a}{\\sin A} = \\frac{b}{\\sin B} = \\frac{c}{\\sin C} = 2R'],
    description: 'Solve oblique non-right triangles given ASA, AAS, or compatible pairs.',
    prerequisites: ['E2'],
    misconceptions: ['SINE_RULE_INVERT_PAIR'],
  },
  H6: {
    id: 'H6',
    level: 3,
    title: 'The Law of Cosines',
    isCore: true,
    formulas: ['c^2 = a^2 + b^2 - 2ab\\cos C, \\quad \\cos C = \\frac{a^2 + b^2 - c^2}{2ab}'],
    description: 'Generalize Pythagoras for SAS and SSS oblique non-right triangles.',
    prerequisites: ['E0', 'E2'],
    misconceptions: ['COSINE_RULE_ORDER_OF_OPS'],
  },
  H7: {
    id: 'H7',
    level: 3,
    title: 'The Ambiguous Case (SSA)',
    isCore: true,
    formulas: ['h = b\\sin A, \\quad \\text{Cases: } 0, 1, \\text{ or } 2 \\text{ valid triangles}'],
    description: 'Classify and completely solve the ambiguous swinging-side configuration.',
    prerequisites: ['H5'],
    misconceptions: ['AMBIG_IGNORED', 'AMBIGUOUS_OBTUSE_CHECK'],
  },
  H8: {
    id: 'H8',
    level: 3,
    title: 'Sinusoidal Modeling: y = A sin(B(x - C)) + D',
    isCore: true,
    formulas: ['\\text{Amp} = |A|, \\; \\text{Period} = \\frac{2\\pi}{|B|}, \\; \\text{Shift} = C, \\; \\text{Midline} = D'],
    description: 'Parameterize, graph, and interpret harmonic sinusoidal wave transformations.',
    prerequisites: ['M6', 'M10'],
    misconceptions: ['PERIOD_SLIP'],
  },
  H9: {
    id: 'H9',
    level: 3,
    title: 'Trigonometric Equations & General Solutions',
    isCore: true,
    formulas: ['\\sin x = k \\implies x = n\\pi + (-1)^n \\alpha, \\quad \\cos x = k \\implies x = 2n\\pi \\pm \\alpha'],
    description: 'Find all solutions on intervals and across all real numbers, including quadratics.',
    prerequisites: ['M7', 'M8'],
    misconceptions: ['GENERAL_MISSING_SOLS'],
  },
  H10: {
    id: 'H10',
    level: 3,
    title: 'Inverse Trigonometric Functions & Principal Domains',
    isCore: true,
    formulas: ['\\arcsin: [-1, 1] \\rightarrow [-\\frac{\\pi}{2}, \\frac{\\pi}{2}], \\quad \\arccos: [-1, 1] \\rightarrow [0, \\pi]'],
    description: 'Evaluate inverse circular functions strictly within their principal value domains.',
    prerequisites: ['E6', 'M6'],
    misconceptions: ['PRINCIPAL_RANGE'],
  },
  H11: {
    id: 'H11',
    level: 3,
    title: 'Navigation Bearings & 3D Spatial Surveying',
    isCore: true,
    formulas: ['\\text{Bearing: 3 digits clockwise from North } (000^\\circ - 360^\\circ)'],
    description: 'Solve multi-plane engineering problems linking horizontal and vertical triangles.',
    prerequisites: ['H5', 'H6'],
    misconceptions: ['BEARING_NOT_FROM_NORTH'],
  },
  H12: {
    id: 'H12',
    level: 3,
    title: 'Ancient Superpowers: Bhāskara & Mādhava',
    isCore: false,
    formulas: ['\\sin\\theta^\\circ \\approx \\frac{4\\theta(180-\\theta)}{40500 - \\theta(180-\\theta)}'],
    description: 'Explore historical Indian rational approximations and infinite series.',
    prerequisites: ['M6'],
    misconceptions: [],
    trickId: 'T10',
  },
};
