// src/content/stations.ts
import type { StationDefinition } from './types';

export const STATIONS_REGISTRY: Record<string, StationDefinition> = {
  // --- LEVEL 1 STATIONS ---
  '1A': {
    id: '1A',
    level: 1,
    title: 'The Shadow Lab',
    subtitle: 'Discover how angle tilt controls the ratio of height to shadow',
    skills: ['E0', 'E3'],
    predictPrompt: 'If you double the height of a flagpole, what happens to the ratio (Height ÷ Shadow) at the same sun angle?',
    predictOptions: [
      'The ratio doubles',
      'The ratio stays exactly the same',
      'The ratio gets cut in half',
      'It depends on the time of year',
    ],
    predictCorrectIdx: 1,
    predictExplanation: 'Similar triangles scale all sides proportionally, so the ratio (Height ÷ Shadow) depends ONLY on the sun angle!',
    testPrompt: 'A 10 m tree casts a 10 m shadow along flat ground. What is the sun elevation angle θ?',
    testOptions: [
      { label: '45° (tan θ = 10/10 = 1)', correct: true, explanation: 'When Opposite = Adjacent, tan θ = 1, which corresponds to 45°.' },
      { label: '30° (tan θ ≈ 0.577)', correct: false, explanation: 'At 30°, the shadow is longer than the tree height.' },
      { label: '60° (tan θ ≈ 1.732)', correct: false, explanation: 'At 60°, the tree height is taller than its shadow.' },
    ],
    exploreGuide: 'Drag the sun elevation slider or change tower height. Notice the live height-to-shadow ratio table.',
    formalizeFormula: '\\tan\\theta = \\frac{\\text{Height}}{\\text{Shadow}} = \\frac{\\text{Opposite}}{\\text{Adjacent}}',
    formalizeRule: 'Tangent is the ratio of the vertical opposite side to the horizontal adjacent side.',
  },
  '1B': {
    id: '1B',
    level: 1,
    title: 'Side Namer & Ratio Builder',
    subtitle: 'Master Hypotenuse, Opposite, and Adjacent relative to angle θ',
    skills: ['E1', 'E2'],
    predictPrompt: 'If you switch your focus from angle A to angle B in the same right triangle, what happens to the Hypotenuse?',
    predictOptions: [
      'The Hypotenuse becomes the Opposite side',
      'The Hypotenuse becomes the Adjacent side',
      'The Hypotenuse stays the same because it is always across from the 90° angle',
      'The Hypotenuse disappears',
    ],
    predictCorrectIdx: 2,
    predictExplanation: 'The Hypotenuse is strictly defined as the side opposite the 90° right angle. It never moves!',
    testPrompt: 'In a right triangle with acute angle θ, Opposite = 3, Adjacent = 4, and Hypotenuse = 5. What is cos θ?',
    testOptions: [
      { label: '4/5 (Adjacent ÷ Hypotenuse)', correct: true, explanation: 'CAH: Cosine is Adjacent over Hypotenuse, so 4/5 = 0.8.' },
      { label: '3/5 (Opposite ÷ Hypotenuse)', correct: false, explanation: '3/5 is sin θ (Opposite over Hypotenuse).' },
      { label: '3/4 (Opposite ÷ Adjacent)', correct: false, explanation: '3/4 is tan θ (Opposite over Adjacent).' },
    ],
    exploreGuide: 'Rotate the triangle and toggle θ between vertex A and B. Watch the sides recolor in real time.',
    formalizeFormula: '\\sin\\theta = \\frac{\\text{Opp}}{\\text{Hyp}}, \\quad \\cos\\theta = \\frac{\\text{Adj}}{\\text{Hyp}}, \\quad \\tan\\theta = \\frac{\\text{Opp}}{\\text{Adj}}',
    formalizeRule: 'SOH-CAH-TOA: Sine is Opp/Hyp, Cosine is Adj/Hyp, Tangent is Opp/Adj.',
  },
  '1C': {
    id: '1C',
    level: 1,
    title: 'Special Angle Forge',
    subtitle: 'Derive exact radical values for 30°, 45°, and 60° without a calculator',
    skills: ['E4', 'E7'],
    predictPrompt: 'Why is sin 30° exactly 1/2?',
    predictOptions: [
      'Because 30 is half of 60',
      'Because cutting an equilateral triangle of side 2 in half creates an opposite side of 1 and hypotenuse of 2',
      'It is just an arbitrary definition by ancient Greeks',
      'Because 30° + 60° = 90°',
    ],
    predictCorrectIdx: 1,
    predictExplanation: 'Cutting an equilateral triangle of side 2 in half yields a right triangle with side 1, side √3, and hypotenuse 2!',
    testPrompt: 'What is the exact value of cos 60°?',
    testOptions: [
      { label: '1/2', correct: true, explanation: 'By the root ladder, cos 60° = sin 30° = √1/2 = 1/2.' },
      { label: '√3/2', correct: false, explanation: '√3/2 is sin 60° or cos 30°.' },
      { label: '√2/2', correct: false, explanation: '√2/2 is cos 45°.' },
    ],
    exploreGuide: 'Fold the 60-60-60 equilateral and 45-45-90 unit square to reveal exact ratios.',
    formalizeFormula: '\\begin{gathered} \\sin(0^\\circ, 30^\\circ, 45^\\circ, 60^\\circ, 90^\\circ) = \\\\ \\frac{\\sqrt{0}}{2}, \\; \\frac{\\sqrt{1}}{2}, \\; \\frac{\\sqrt{2}}{2}, \\; \\frac{\\sqrt{3}}{2}, \\; \\frac{\\sqrt{4}}{2} \\end{gathered}',
    formalizeRule: 'The Root Pattern: square root of 0, 1, 2, 3, 4 all divided by 2!',
  },
  '1D': {
    id: '1D',
    level: 1,
    title: 'Missing-Side Solver',
    subtitle: 'Master the 5-step SCALE routine to solve real-world heights',
    skills: ['E5', 'E6', 'E8', 'E9'],
    predictPrompt: 'When solving for an unknown side in a right triangle, when do you multiply versus divide?',
    predictOptions: [
      'Multiply if the unknown is in the numerator (top); divide if it is in the denominator (bottom)',
      'Always multiply by the angle value',
      'Always divide by the hypotenuse',
      'It does not matter, both operations give the same result',
    ],
    predictCorrectIdx: 0,
    predictExplanation: 'Cross-multiplying fractions shows: if x is on top (e.g. sin θ = x/h), x = h · sin θ. If x is on bottom (e.g. cos θ = a/x), x = a / cos θ!',
    testPrompt: 'A surveyor stands 40 m from a tower and measures an elevation angle of 30° to the top. How tall is the tower? (tan 30° ≈ 0.577)',
    testOptions: [
      { label: '23.1 m (40 × tan 30°)', correct: true, explanation: 'Height = Distance × tan 30° = 40 × 0.577 = 23.1 m.' },
      { label: '69.3 m (40 ÷ tan 30°)', correct: false, explanation: 'The unknown height is in the numerator (top), so multiply, do not divide!' },
      { label: '20.0 m (40 × sin 30°)', correct: false, explanation: '40 m is the adjacent ground distance, so use tan, not sin.' },
    ],
    exploreGuide: 'Step through the SCALE method to calculate missing ramp heights, tower elevations, and kite strings.',
    formalizeFormula: '\\begin{gathered} \\text{SCALE: } \\text{Sketch} \\rightarrow \\text{Choose } \\theta \\rightarrow \\text{Assign (O, A, H)} \\\\ \\text{Link Ratio} \\rightarrow \\text{Evaluate Unknown } x \\\\ x = \\text{Hyp} \\cdot \\sin\\theta \\quad \\Big| \\quad x = \\frac{\\text{Adj}}{\\cos\\theta} \\end{gathered}',
    formalizeRule: 'If the unknown is on top of the fraction, multiply; if on the bottom, divide!',
  },

  // --- LEVEL 2 STATIONS ---
  '2A': {
    id: '2A',
    level: 2,
    title: 'Unit Circle Playground',
    subtitle: 'Coordinates as trigonometry for any angle up to 360° and beyond',
    skills: ['M6', 'M7', 'M8', 'M9'],
    predictPrompt: 'If angle θ is in Quadrant 2 (between 90° and 180°), what are the signs of cos θ and sin θ?',
    predictOptions: [
      'Both are positive',
      'cos θ is negative, sin θ is positive',
      'cos θ is positive, sin θ is negative',
      'Both are negative',
    ],
    predictCorrectIdx: 1,
    predictExplanation: 'In Quadrant 2, x-coordinates are negative (cos) and y-coordinates are positive (sin)!',
    testPrompt: 'In Quadrant 3 (180° < θ < 270°), what are the signs of coordinates (x, y) = (cos θ, sin θ)?',
    testOptions: [
      { label: '(-, -) — Both cos θ and sin θ are negative', correct: true, explanation: 'In Q3, both x and y are negative, meaning tan θ = y/x is positive.' },
      { label: '(-, +) — cos is negative, sin is positive', correct: false, explanation: '(-, +) is Quadrant 2.' },
      { label: '(+, -) — cos is positive, sin is negative', correct: false, explanation: '(+, -) is Quadrant 4.' },
    ],
    exploreGuide: 'Drag point P around the circle. Watch x (cos) and y (sin) projections and the ASTC quadrant lights.',
    formalizeFormula: 'P(\\theta) = (\\cos\\theta, \\sin\\theta), \\quad \\alpha = 180^\\circ - \\theta \\text{ in Q2}',
    formalizeRule: 'ASTC: All positive in Q1, Sin in Q2, Tan in Q3, Cos in Q4. Reference angles measure to the x-axis.',
  },
  '2B': {
    id: '2B',
    level: 2,
    title: 'Wave Tracer',
    subtitle: 'Why rotating around a circle draws a continuous sinusoidal wave',
    skills: ['M6', 'M9'],
    predictPrompt: 'If you trace the vertical height of a point moving around a circle at constant speed, what curve does it make?',
    predictOptions: [
      'A straight diagonal line',
      'A smooth sinusoidal sine wave',
      'A zigzag sawtooth pattern',
      'A series of semicircles',
    ],
    predictCorrectIdx: 1,
    predictExplanation: 'Because vertical height is y = R · sin(θ), steady rotation unrolls directly into a sine wave!',
    testPrompt: 'What is the period of the function y = sin(2x) in radians?',
    testOptions: [
      { label: 'π radians (2π ÷ 2 = π)', correct: true, explanation: 'Period = 2π / B. Here B = 2, so Period = 2π / 2 = π.' },
      { label: '2π radians', correct: false, explanation: '2π is the period of standard sin(x).' },
      { label: '4π radians', correct: false, explanation: 'A frequency B > 1 compresses the wave period.' },
    ],
    exploreGuide: 'Spin the rotating wheel and watch the synchronized height projection unroll into a sine wave.',
    formalizeFormula: 'y(t) = \\sin(t), \\quad \\cos(t) = \\sin(t + 90^\\circ)',
    formalizeRule: 'Cosine is simply a sine wave phase-shifted to the left by 90 degrees (π/2 radians).',
  },
  '2C': {
    id: '2C',
    level: 2,
    title: 'Radian Roller',
    subtitle: 'Measure angles by walking the circle’s own radius along the rim',
    skills: ['M10', 'M11'],
    predictPrompt: 'How many radii wrap around a full circle circumference?',
    predictOptions: ['Exactly 3', 'Exactly 4', 'Exactly 2π ≈ 6.28', 'Exactly 360'],
    predictCorrectIdx: 2,
    predictExplanation: 'Circumference is 2πr, so exactly 2π radii wrap around the entire rim! That is why 360° = 2π radians.',
    testPrompt: 'Convert 180° into radians:',
    testOptions: [
      { label: 'π radians (≈ 3.14159)', correct: true, explanation: 'A half circle circumference wraps exactly π radius lengths.' },
      { label: '2π radians', correct: false, explanation: '2π is a full 360° turn.' },
      { label: 'π/2 radians', correct: false, explanation: 'π/2 is a quarter turn (90°).' },
    ],
    exploreGuide: 'Roll the wheel along the ribbon track to see 1 radian, π radians (180°), and 2π radians (360°).',
    formalizeFormula: '\\pi \\text{ rad} = 180^\\circ, \\quad s = r\\theta, \\quad A = \\frac{1}{2}r^2\\theta',
    formalizeRule: 'Arc length equals radius times angle in radians; sector area is half r-squared theta.',
  },
  '2D': {
    id: '2D',
    level: 2,
    title: 'The Identity Lab',
    subtitle: 'Connect the right triangle, the unit circle, and Pythagoras',
    skills: ['M1', 'M2', 'M3', 'M4', 'M5'],
    predictPrompt: 'In any right triangle with acute angle θ, what is the value of sin²θ + cos²θ?',
    predictOptions: [
      'It depends on the angle θ',
      'Always exactly 1',
      'It depends on the size of the triangle',
      'Always 0',
    ],
    predictCorrectIdx: 1,
    predictExplanation: 'By the Pythagorean theorem, Opp² + Adj² = Hyp². Dividing by Hyp² gives (Opp/Hyp)² + (Adj/Hyp)² = 1, so sin²θ + cos²θ is always identically 1!',
    testPrompt: 'If sin θ = 3/5, what is cos²θ?',
    testOptions: [
      { label: '16/25 (1 - sin²θ = 1 - 9/25)', correct: true, explanation: 'By the Pythagorean identity: cos²θ = 1 - sin²θ = 1 - 9/25 = 16/25.' },
      { label: '9/25', correct: false, explanation: '9/25 is sin²θ.' },
      { label: '4/5', correct: false, explanation: '4/5 is cos θ, whereas cos²θ is (4/5)² = 16/25.' },
    ],
    exploreGuide: 'Observe the unit triangle with hypotenuse 1. Divide by cos² or sin² to discover all 3 Pythagorean identities.',
    formalizeFormula: '\\sin^2\\theta + \\cos^2\\theta = 1, \\quad 1 + \\tan^2\\theta = \\sec^2\\theta, \\quad 1 + \\cot^2\\theta = \\csc^2\\theta',
    formalizeRule: 'Because x² + y² = 1 on the unit circle, cos²θ + sin²θ identically equals 1 for ANY angle.',
  },
  '2E': {
    id: '2E',
    level: 2,
    title: 'Height & Distance Studio',
    subtitle: 'Solve complex two-observer problems sharing a common vertical baseline',
    skills: ['M12', 'M13'],
    predictPrompt: 'If you want to measure the height of a mountain you cannot climb, how many elevation angles must you measure from the ground?',
    predictOptions: [
      'Only 1 angle',
      'At least 2 angles from two different known baseline distances',
      'At least 10 angles',
      'It is mathematically impossible',
    ],
    predictCorrectIdx: 1,
    predictExplanation: 'Two observers or two positions create two simultaneous tangent equations, allowing you to solve for both height and distance!',
    testPrompt: 'A surveyor measures a lighthouse from two points 50 m apart along a line: angle 30° and angle 45°. How is the height calculated?',
    testOptions: [
      { label: 'h = 50 ÷ (cot 30° - cot 45°)', correct: true, explanation: 'Subtracting baseline distances x1 - x2 = h(cot 30° - cot 45°) = 50.' },
      { label: 'h = 50 × sin 30° × cos 45°', correct: false, explanation: 'Non-right triangle baselines require cotangent subtraction.' },
      { label: 'h = 50 ÷ (tan 45° + tan 30°)', correct: false, explanation: 'Angles are on the same side of the vertical, so cotangents subtract.' },
    ],
    exploreGuide: 'Set up dual tangent equations from two observation baselines to measure mountains and lighthouses.',
    formalizeFormula: 'h = \\frac{d}{\\cot\\alpha - \\cot\\beta}, \\quad \\text{Area} = \\frac{1}{2}ab\\sin C',
    formalizeRule: 'Equate the shared vertical height h across two right triangles to eliminate unknown distances.',
  },

  // --- LEVEL 3 STATIONS ---
  '3A': {
    id: '3A',
    level: 3,
    title: 'The Angle Mixer',
    subtitle: 'Discover why sin(A + B) ≠ sin A + sin B through compound rotations',
    skills: ['H2', 'H3'],
    predictPrompt: 'Does sin(30° + 30°) equal sin 30° + sin 30°?',
    predictOptions: [
      'Yes, sine distributes across addition',
      'No, because sin 60° = √3/2 ≈ 0.866, while sin 30° + sin 30° = 1/2 + 1/2 = 1.0',
      'Only for acute angles',
      'Only when angles are in radians',
    ],
    predictCorrectIdx: 1,
    predictExplanation: 'Trigonometric functions are non-linear! You must use the compound Angle Mixer formulas.',
    testPrompt: 'Expand sin(A + B) using the compound angle identity:',
    testOptions: [
      { label: 'sin A cos B + cos A sin B', correct: true, explanation: 'The sine compound identity mixes sine and cosine terms.' },
      { label: 'sin A sin B + cos A cos B', correct: false, explanation: 'That is part of the cosine difference identity.' },
      { label: 'sin A + sin B', correct: false, explanation: 'Trigonometric functions are non-linear; they never distribute.' },
    ],
    exploreGuide: 'Combine angle A and angle B on the unit circle and observe the geometric projection rectangles.',
    formalizeFormula: '\\sin(A \\pm B) = \\sin A\\cos B \\pm \\cos A\\sin B, \\quad \\sin 2A = 2\\sin A\\cos A',
    formalizeRule: 'Compound angle formulas let us compute exact values for 75° (45° + 30°) and 15° (45° - 30°).',
  },
  '3B': {
    id: '3B',
    level: 3,
    title: 'Wave Interference Studio',
    subtitle: 'Acoustic cancellation and transformation parameters A, B, C, D',
    skills: ['H8', 'H4'],
    predictPrompt: 'How can two active sound waves cancel each other out to create complete silence?',
    predictOptions: [
      'By turning down the speaker volume',
      'By playing a second identical wave shifted by 180° (π radians)',
      'By increasing wave frequency to infinity',
      'Sound waves cannot cancel each other',
    ],
    predictCorrectIdx: 1,
    predictExplanation: 'When peaks align with troughs (180° phase shift), sin(t) + sin(t + 180°) = sin(t) - sin(t) = 0!',
    testPrompt: 'Two sound waves sin(t) and sin(t + φ) combine to produce silence. What is the phase shift φ?',
    testOptions: [
      { label: '180° (π radians)', correct: true, explanation: 'sin(t + 180°) = -sin(t), so sin(t) + (-sin(t)) = 0 (Destructive Interference).' },
      { label: '90° (π/2 radians)', correct: false, explanation: 'A 90° shift produces cos(t), not cancellation.' },
      { label: '360° (2π radians)', correct: false, explanation: 'A 360° shift leaves the wave identical, doubling the sound!' },
    ],
    exploreGuide: 'Adjust sliders for Amplitude, Period, Phase Shift, and Midline to match physical wave signals.',
    formalizeFormula: 'y = A\\sin(B(x - C)) + D, \\quad \\text{Period} = \\frac{2\\pi}{|B|}',
    formalizeRule: 'A controls height, B compresses wavelength, C shifts horizontally, and D sets vertical center.',
  },
  '3C': {
    id: '3C',
    level: 3,
    title: 'Triangle Solver Lab',
    subtitle: 'The Law of Sines, Law of Cosines, and the SSA Ambiguous Case',
    skills: ['H5', 'H6', 'H7'],
    predictPrompt: 'In the SSA condition (given an angle and two sides), how many distinct triangles can be formed?',
    predictOptions: [
      'Always exactly 1',
      'Depending on the side lengths, 0, 1, or 2 triangles can form',
      'Always 3 triangles',
      'An infinite number of triangles',
    ],
    predictCorrectIdx: 1,
    predictExplanation: 'This is the Ambiguous Case: if the swinging side is between the altitude and the other side (h < a < b), it touches the baseline in two places!',
    testPrompt: 'In triangle ABC with angle A = 30° and side b = 10, the altitude is h = 10 sin 30° = 5. If side a = 7, how many triangles exist?',
    testOptions: [
      { label: '2 triangles (h < a < b)', correct: true, explanation: 'Because 5 < 7 < 10, the side swings through the baseline at two points.' },
      { label: '1 unique triangle', correct: false, explanation: '1 triangle occurs when a ≥ b or a = h.' },
      { label: '0 triangles', correct: false, explanation: '0 triangles occurs when a < h (too short to reach).' },
    ],
    exploreGuide: 'Drag side a on the swinging arc to see when 0, 1, or 2 non-right triangles exist.',
    formalizeFormula: '\\frac{a}{\\sin A} = \\frac{b}{\\sin B} = \\frac{c}{\\sin C}, \\quad c^2 = a^2 + b^2 - 2ab\\cos C',
    formalizeRule: 'When h < a < b, the swinging side intersects the baseline at TWO distinct points: 2 triangles!',
  },
  '3D': {
    id: '3D',
    level: 3,
    title: 'The Proof Builder',
    subtitle: 'Master the one-sided transformation protocol for analytic proofs',
    skills: ['H1'],
    predictPrompt: 'When proving a trigonometric identity, is it valid to move terms across the equals sign?',
    predictOptions: [
      'Yes, like solving any algebraic equation',
      'No! You must transform one side independently until it identically equals the other',
      'Only if you divide by cosine first',
      'Only in Level 3',
    ],
    predictCorrectIdx: 1,
    predictExplanation: 'Moving across the equals sign assumes the identity is already true! Valid proofs transform LHS to RHS strictly by substitution.',
    testPrompt: 'What is the best initial algebraic step to prove tan θ + cot θ = sec θ csc θ?',
    testOptions: [
      { label: 'Express tan θ as sin/cos and cot θ as cos/sin', correct: true, explanation: 'Converting all non-standard functions into fundamental sin and cos makes the algebra transparent.' },
      { label: 'Cross-multiply across the equals sign', correct: false, explanation: 'In analytic proof protocol, never cross-multiply across the equals sign.' },
      { label: 'Square both sides of the identity', correct: false, explanation: 'Squaring may introduce extraneous false roots.' },
    ],
    exploreGuide: 'Arrange valid algebraic move cards to prove trigonometric identities step-by-step.',
    formalizeFormula: '\\text{Convert to } \\sin/\\cos \\rightarrow \\text{Common Denominator} \\rightarrow \\text{Pythagorean Swap}',
    formalizeRule: 'Never move terms across the equals sign! Work on the complex side until it identically matches the target.',
  },
  '3E': {
    id: '3E',
    level: 3,
    title: 'Equation Detective',
    subtitle: 'Find all solutions on intervals and general solutions across all real numbers',
    skills: ['H9', 'H10'],
    predictPrompt: 'Why does an equation like sin x = 1/2 have infinitely many solutions across all real numbers?',
    predictOptions: [
      'Because the sine function repeats periodically every 360° (2π radians) indefinitely',
      'Because of rounding errors on calculators',
      'It only has 1 solution, not infinitely many',
      'Because x can only be negative',
    ],
    predictCorrectIdx: 0,
    predictExplanation: 'Trigonometric functions are periodic! Adding any integer multiple of 2π (2nπ) lands on the exact same coordinate.',
    testPrompt: 'How many solutions does sin x = 1/2 have in the interval [0, 360°)?',
    testOptions: [
      { label: '2 solutions (30° and 150°)', correct: true, explanation: 'Sine is positive in Quadrant 1 (30°) and Quadrant 2 (180° - 30° = 150°).' },
      { label: '1 solution (only 30°)', correct: false, explanation: 'Remember ASTC: Sine is positive in both Q1 and Q2.' },
      { label: '4 solutions', correct: false, explanation: 'In Q3 and Q4, sine is negative.' },
    ],
    exploreGuide: 'Intersect y = sin x with target horizontal lines and map solutions around the Unit Circle.',
    formalizeFormula: '\\sin x = k \\implies x = n\\pi + (-1)^n\\alpha, \\quad \\cos x = k \\implies x = 2n\\pi \\pm \\alpha',
    formalizeRule: 'Sine is positive in Q1 & Q2; Cosine in Q1 & Q4; Tangent in Q1 & Q3. For quadratics, factor and check domains.',
  },
  '3F': {
    id: '3F',
    level: 3,
    title: 'Ancient Superpowers (Boost)',
    subtitle: 'Test 7th-century rational approximations and Mādhava’s infinite series',
    skills: ['H12'],
    predictPrompt: 'Did ancient mathematicians know how to calculate accurate sine values before modern calculators?',
    predictOptions: [
      'No, trigonometry was invented in the 20th century',
      'Yes, through geometric chords, rational formulas, and infinite series',
      'Only for 90° angles',
      'They only used physical ropes with knots',
    ],
    predictCorrectIdx: 1,
    predictExplanation: 'Mathematicians like Hipparchus, Ptolemy, Āryabhaṭa, Bhāskara I, and Mādhava developed sophisticated methods to calculate trigonometric values with incredible accuracy!',
    testPrompt: 'What was Bhāskara I’s rational approximation formula used for in the 7th century?',
    testOptions: [
      { label: 'Approximating sine values to within 1% without any square roots or tables', correct: true, explanation: 'Bhāskara’s fractional formula 4θ(180-θ)/(40500 - θ(180-θ)) accurately computes sine with remarkable precision.' },
      { label: 'Proving the Pythagorean theorem', correct: false, explanation: 'It is specifically a rational formula for sine.' },
      { label: 'Calculating logarithms', correct: false, explanation: 'Logarithms were invented centuries later.' },
    ],
    exploreGuide: 'Benchmark Bhāskara’s rational formula and watch Mādhava’s infinite polynomial converge to the true sine.',
    formalizeFormula: '\\sin\\theta^\\circ \\approx \\frac{4\\theta(180-\\theta)}{40500 - \\theta(180-\\theta)}, \\quad \\sin x = x - \\frac{x^3}{3!} + \\frac{x^5}{5!} - \\dots',
    formalizeRule: 'Historical Indian mathematicians calculated trigonometric values to high accuracy centuries before calculus.',
  },
};
