// src/content/story.ts
import type { StoryPanel } from './types';

export const STORY_PANELS: StoryPanel[] = [
  // --- LEVEL 1: SHADOW SCOUTS ---
  {
    id: 'story-1-1',
    level: 1,
    panelNumber: 1,
    title: 'The Meridian Express',
    setting: 'Giza Plateau, Egypt — Sunrise',
    artPrompt: 'A steampunk brass time-train arriving before the Great Pyramids at dawn.',
    displayText: 'The Meridian Express rolls to a stop before the Great Pyramid of Giza. Nobody can climb this ancient wonder with a measuring tape. Apprentice surveyors, Theo has your first mission!',
    spokenText: 'The Meridian Express rolls to a stop before the Great Pyramid of Giza. Nobody can climb this ancient wonder with a measuring tape. Apprentice surveyors, Theo has your first mission.',
    image: '/story/story-1-1.jpg',
    audio: '/audio/story-1-1.mp3',
  },
  {
    id: 'story-1-2',
    level: 1,
    panelNumber: 2,
    title: 'Thales and the Staff',
    setting: 'Giza Desert, c. 600 BCE',
    artPrompt: 'Ancient Greek philosopher Thales planting an upright wooden staff in the sand.',
    displayText: 'As ancient stories tell, the philosopher Thales planted his staff in the desert sand. He did not climb. He waited until his own shadow was exactly as long as his staff.',
    spokenText: 'As ancient stories tell, the philosopher Thales planted his staff in the desert sand. He did not climb. He waited until his own shadow was exactly as long as his staff.',
    image: '/story/story-1-2.jpg',
    audio: '/audio/story-1-2.mp3',
  },
  {
    id: 'story-1-3',
    level: 1,
    panelNumber: 3,
    title: 'The Shifting Sun',
    setting: 'Giza Desert, Late Afternoon',
    artPrompt: 'Kofi and Ira measuring a stick shadow with a glowing similar triangle overlay.',
    displayText: 'Later in the afternoon, the sun dips. Kofi measures a 2-meter rod casting a 3.5-meter shadow. Ira notices: the triangle made by the staff has the exact same shape as the giant triangle made by the pyramid!',
    spokenText: 'Later in the afternoon, the sun dips. Kofi measures a two-meter rod casting a three-point-five meter shadow. Ira notices: the triangle made by the staff has the exact same shape as the giant triangle made by the pyramid.',
    image: '/story/story-1-3.jpg',
    audio: '/audio/story-1-3.mp3',
  },
  {
    id: 'story-1-4',
    level: 1,
    panelNumber: 4,
    title: 'Measuring the Earth',
    setting: 'Alexandria, c. 240 BCE',
    artPrompt: 'Eratosthenes comparing sun angles in deep wells between Syene and Alexandria.',
    displayText: 'In Alexandria, Eratosthenes realized that shadows cast in two distant cities revealed the curvature of the world. With simple angles and footsteps, humanity measured the circumference of the Earth.',
    spokenText: 'In Alexandria, Eratosthenes realized that shadows cast in two distant cities revealed the curvature of the world. With simple angles and footsteps, humanity measured the circumference of the Earth.',
    image: '/story/story-1-4.jpg',
    audio: '/audio/story-1-4.mp3',
  },
  {
    id: 'story-1-5',
    level: 1,
    panelNumber: 5,
    title: 'The Naming of the Ratios',
    setting: 'Meridian Express Observatory Car',
    artPrompt: 'Mei sketching three fraction tiles while Theo stamps them with brass seals.',
    displayText: 'Aboard the train, Mei names the three sacred ratios: opposite over hypotenuse, adjacent over hypotenuse, and opposite over adjacent. Theo stamps them with their true names: Sine, Cosine, and Tangent.',
    spokenText: 'Aboard the train, Mei names the three sacred ratios: opposite over hypotenuse, adjacent over hypotenuse, and opposite over adjacent. Theo stamps them with their true names: Sine, Cosine, and Tangent.',
    image: '/story/story-1-5.jpg',
    audio: '/audio/story-1-5.mp3',
  },
  {
    id: 'story-1-6',
    level: 1,
    panelNumber: 6,
    title: 'The Call to the Field',
    setting: 'Observation Deck with Star Map',
    artPrompt: 'Theo unlatching a gleaming brass clinometer, projecting glowing angles into the sky.',
    displayText: 'Theo unlatches the brass clinometer. "Give me an angle and a single baseline distance, and together we will measure anything tall."',
    spokenText: 'Theo unlatches the brass clinometer. Give me an angle and a single baseline distance, and together we will measure anything tall.',
    image: '/story/story-1-6.jpg',
    audio: '/audio/story-1-6.mp3',
  },

  // --- LEVEL 2: CIRCLE CARTOGRAPHERS ---
  {
    id: 'story-2-1',
    level: 2,
    panelNumber: 1,
    title: 'The Astronomers of Kusumapura',
    setting: 'Pataliputra (Patna), India, 499 CE',
    artPrompt: 'Aryabhata unrolling astronomical palm-leaf tables under an ancient starry sky.',
    displayText: 'In ancient India, the astronomer Aryabhata mapped the heavens using bowstrings called jya. Instead of flat triangles, he placed angles inside circles.',
    spokenText: 'In ancient India, the astronomer Aryabhata mapped the heavens using bowstrings called jya. Instead of flat triangles, he placed angles inside circles.',
    image: '/story/story-2-1.jpg',
    audio: '/audio/story-2-1.mp3',
  },
  {
    id: 'story-2-2',
    level: 2,
    panelNumber: 2,
    title: 'The Circle of Radius One',
    setting: 'Aryabhata’s Observatory',
    artPrompt: 'Diagram of a glowing circle with radius normalized to exactly one.',
    displayText: 'Calculating ratios for different planetary spheres was tedious. Aryabhata simplified everything by setting the circle’s radius to exactly one. The Unit Circle was born.',
    spokenText: 'Calculating ratios for different planetary spheres was tedious. Aryabhata simplified everything by setting the circles radius to exactly one. The Unit Circle was born.',
    image: '/story/story-2-2.jpg',
    audio: '/audio/story-2-2.mp3',
  },
  {
    id: 'story-2-3',
    level: 2,
    panelNumber: 3,
    title: 'Coordinates as Ratios',
    setting: 'A Giant Glowing Coordinate Plane',
    artPrompt: 'Ira walking on a Cartesian grid with a rotating beam sweeping past 90 degrees.',
    displayText: 'Ira watches the rotating beam sweep past ninety degrees. A right triangle cannot have an angle of 120°, but a circle can! The horizontal position is cosine; the vertical position is sine.',
    spokenText: 'Ira watches the rotating beam sweep past ninety degrees. A right triangle cannot have an angle of one hundred and twenty degrees, but a circle can! The horizontal position is cosine; the vertical position is sine.',
    image: '/story/story-2-3.jpg',
    audio: '/audio/story-2-3.mp3',
  },
  {
    id: 'story-2-4',
    level: 2,
    panelNumber: 4,
    title: 'The Journey of a Word',
    setting: 'Ancient Silk Road & Mediterranean Sea',
    artPrompt: 'Parchment showing Sanskrit jya turning into Arabic jiba, Latin sinus, and English Sine.',
    displayText: 'Mateo traces the word’s thousand-year journey. The Sanskrit word jya traveled to Arabic as jiba, was translated into Latin as sinus meaning a fold or bay, and finally became our English word: Sine.',
    spokenText: 'Mateo traces the words thousand-year journey. The Sanskrit word jya traveled to Arabic as jiba, was translated into Latin as sinus meaning a fold or bay, and finally became our English word: Sine.',
    image: '/story/story-2-4.jpg',
    audio: '/audio/story-2-4.mp3',
  },
  {
    id: 'story-2-5',
    level: 2,
    panelNumber: 5,
    title: 'Walking the Rim',
    setting: 'Mountain Observatory Track',
    artPrompt: 'Kofi rolling a wheel along a circular rim, uncoiling a ribbon of length r.',
    displayText: 'Degrees are arbitrary human divisions. Kofi wraps the circle’s own radius along its curved rim. Walking exactly one radius marks one radian. Walking π radians turns a perfect half-circle.',
    spokenText: 'Degrees are arbitrary human divisions. Kofi wraps the circles own radius along its curved rim. Walking exactly one radius marks one radian. Walking pi radians turns a perfect half-circle.',
    image: '/story/story-2-5.jpg',
    audio: '/audio/story-2-5.mp3',
  },
  {
    id: 'story-2-6',
    level: 2,
    panelNumber: 6,
    title: 'The Great Identity Map',
    setting: 'The Celestial Observatory',
    artPrompt: 'Theo aligning a right triangle inside the unit circle highlighting sin² + cos² = 1.',
    displayText: 'Theo links the unit circle directly to Pythagoras. Because the hypotenuse is always one, sine squared plus cosine squared must always equal one. We are ready to map the full circle!',
    spokenText: 'Theo links the unit circle directly to Pythagoras. Because the hypotenuse is always one, sine squared plus cosine squared must always equal one. We are ready to map the full circle!',
    image: '/story/story-2-6.jpg',
    audio: '/audio/story-2-6.mp3',
  },

  // --- LEVEL 3: SKY ENGINEERS ---
  {
    id: 'story-3-1',
    level: 3,
    panelNumber: 1,
    title: 'The Kerala Mathematicians',
    setting: 'Sangamagrama, Kerala, 14th Century',
    artPrompt: 'Mādhava writing mathematical polynomial series in sand under palm trees.',
    displayText: 'At the Kerala school of mathematics, Mādhava discovered that sine and cosine could be computed to infinite decimal precision using infinite series, centuries before European calculus.',
    spokenText: 'At the Kerala school of mathematics, Mādhava discovered that sine and cosine could be computed to infinite decimal precision using infinite series, centuries before European calculus.',
    image: '/story/story-3-1.jpg',
    audio: '/audio/story-3-1.mp3',
  },
  {
    id: 'story-3-2',
    level: 3,
    panelNumber: 2,
    title: 'Ships in the Fog',
    setting: 'A Foggy Coastal Harbor',
    artPrompt: 'Mateo steering a ship between two distant coastal lighthouses forming an oblique triangle.',
    displayText: 'A ship navigates through dense fog between two distant lighthouses. The triangle formed with the coastline has no right angle. SOH-CAH-TOA alone cannot save them.',
    spokenText: 'A ship navigates through dense fog between two distant lighthouses. The triangle formed with the coastline has no right angle. SOH-CAH-TOA alone cannot save them.',
    image: '/story/story-3-2.svg',
    audio: '/audio/story-3-2.mp3',
  },
  {
    id: 'story-3-3',
    level: 3,
    panelNumber: 3,
    title: 'The Altitude Split',
    setting: 'Navigator’s Chart Table',
    artPrompt: 'Kofi drawing an altitude line dividing an oblique triangle into two right-angled halves.',
    displayText: 'Kofi drops a vertical altitude down the center. By sharing a common height between two right triangles, the Law of Sines is revealed: every side divided by the sine of its opposite angle is perfectly equal.',
    spokenText: 'Kofi drops a vertical altitude down the center. By sharing a common height between two right triangles, the Law of Sines is revealed: every side divided by the sine of its opposite angle is perfectly equal.',
    image: '/story/story-3-3.svg',
    audio: '/audio/story-3-3.mp3',
  },
  {
    id: 'story-3-4',
    level: 3,
    panelNumber: 4,
    title: 'Correcting Pythagoras',
    setting: 'Naval Engineering Workshop',
    artPrompt: 'Ira demonstrating how non-right angles stretch or shrink the hypotenuse.',
    displayText: 'When the angle between two known sides is not ninety degrees, Pythagoras needs an adjustment. The Law of Cosines applies a smooth correction term, handling any triangle in the universe.',
    spokenText: 'When the angle between two known sides is not ninety degrees, Pythagoras needs an adjustment. The Law of Cosines applies a smooth correction term, handling any triangle in the universe.',
    image: '/story/story-3-4.svg',
    audio: '/audio/story-3-4.mp3',
  },
  {
    id: 'story-3-5',
    level: 3,
    panelNumber: 5,
    title: 'Harmonic Waves',
    setting: 'Acoustic Synthesis Studio',
    artPrompt: 'Mei tuning dual harmonic frequency dials on an oscilloscope.',
    displayText: 'Mei blends musical chords on an audio synthesizer. Combining two pure sine waves creates complex harmonics, governed by the compound angle formulas that power wireless communication.',
    spokenText: 'Mei blends musical chords on an audio synthesizer. Combining two pure sine waves creates complex harmonics, governed by the compound angle formulas that power wireless communication.',
    image: '/story/story-3-5.svg',
    audio: '/audio/story-3-5.mp3',
  },
  {
    id: 'story-3-6',
    level: 3,
    panelNumber: 6,
    title: 'The Master Surveyor Commission',
    setting: 'Sky Surveyor Celestial Proving Grounds',
    artPrompt: 'Theo standing atop a modern observatory bridge with all four apprentices.',
    displayText: 'Theo turns to you with his telescope gleaming: "You have mastered shadows and conquered the unit circle. Now, prove your identities and build the world. Welcome, Sky Engineer!"',
    spokenText: 'Theo turns to you with his telescope gleaming: You have mastered shadows and conquered the unit circle. Now, prove your identities and build the world. Welcome, Sky Engineer!',
    image: '/story/story-3-6.svg',
    audio: '/audio/story-3-6.mp3',
  },
];
